# action.yml
name: 'Publish WebApp build content'
author: 'Kirill Scherba'
description: 'Publish WebApp build content to web server with rsync'

# branding:
#   icon: arrow-right
#   color: purple

# Input parameters description
inputs:

  server_name: # id of input 1
    description: 'Publish server name or IP address'
    required: true

  server_folder:  
    description: 'Publish server folder name'
    required: true
    default: '/publish'

  server_user_name:
    description: 'Publish server user name'
    required: true
    default: 'root'

  source_folder: 
    description: 'This projects dist folder with content to publish'
    required: true
    default: './dist'

# Output parameters description
outputs:

  time: # id of output 1
    description: 'The time of publish processing'

# Runs (execute action in docker container)
runs:

  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.server_name }}      # $1
    - ${{ inputs.server_folder }}    # $2
    - ${{ inputs.server_user_name }} # $3
    - ${{ inputs.source_folder }}    # $4
